FROM tensorflow/tensorflow:2.3.0-gpu-jupyter as base

RUN apt-get update \
        && apt-get install -y libsm6 libxext6 libxrender-dev libgl1-mesa-glx \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 --no-cache-dir install flask \
    pillow \
    opencv-python \
    scikit-image \
    pytesseract \
	tensorflow_model_optimization \
	imgaug \
	keras_applications \
	tqdm \
	tqdm \
	transformers==3.5.0 \
	Unidecode==1.1.1 \
	numpy==1.18.5 \
	pandas==1.1.2 \
	seqeval==1.2.2 \
	tensorboard==2.3.0 \
	tensorboard-plugin-profile==2.3.0 \
	tensorboard-plugin-wit==1.7.0 \
	tensorflow==2.3.0 \
	tensorflow-addons==0.11.2 \
	tensorflow-estimator==2.3.0 \
	tensorflow-model-optimization==0.5.0 \
	nltk \
	jupyter \
    seaborn \
	tokenizers==0.9.3


RUN python -m nltk.downloader punkt
RUN pip3 install torch==1.7.0+cu101 torchvision==0.8.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html
